config/routes.rb
Rails.application.routes.draw do

  root to: 'static_pages#index'

  get '/auth/:provider/callback', to: 'sessions#create'
  get '/signout',                 to: 'sessions#destroy', as: 'signout'
  get '/search',                  to: 'mentors#search'
  get 'profile_type_prompt',      to: 'static_pages#profile_type_prompt'

  post 'notifications/notify',    to: 'notifications#notify'

  resources :snippets, only: [:new]
  resources :preferences
  resources :mentors
  resources :skills
  resources :students
  resources :users, only: [:update]
  resources :appointments, only: [:create]


end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
before_action :get_mentors, only: [:index]
before_action :get_student, only: [:index]

  def index
  end

  def profile_type_prompt
    @user = current_user
  end

private

  def get_mentors
    @mentors = Mentor.all.sample(3)
  end

  def get_student
    @student = Student.all.sample(3).pop
  end
end

app/views/static_pages/index.html.erb
<div class="site-wrapper">
  <div class="site-wrapper-inner">
    <div class="cover-container">
      <div class="inner cover">
        <p class="home-logo lead">
          <%=image_tag("whiteline.gif", size: "443x373") %>
        </p>
      </div>
    </div>

    <div class="jumbotron">
      <div class="panel panel-default">
        <div class="panel-body">
          <h1>
            <span class="glyphicon glyphicon-list" aria-hidden="true"></span>
            Browse Turing Mentors
          </h1>
          <p class="col-lg-4 col-lg-offset-4">Learn about all of the mentors at Turing in one convient place. Who they are, their expertise, and their backgrounds</p>
        </div>
      </div>

      <div class="container marketing">
        <div class="row">
          <% if @mentor %>
          <% @mentors.each do |m| %>
          <div class="col-lg-4">
            <%= image_tag m.photo.url(:thumb), class: "img-circle" %>
            <h2><%= link_to m.name, mentor_path(m) %></h2>
            <p>
              <% m.skills.each do |skill| %>
              <%= skill.name %> &nbsp
              <% end %>
            </p>
          </div><!-- /.col-lg-4 -->
          <% end %>
          <% end %>
        </div><!-- /.row -->
      </div>
    </div>

    <div class="jumbotron">
      <div class="panel panel-default">
        <div class="panel-body">
          <h1>
            <span class="glyphicon glyphicon-user" aria-hidden="true"></span>
            Build a Student Profile
          </h1>
          <p class="col-lg-4 col-lg-offset-4">Your profile allows you to easily share information about your current learning at Turing. Take the guess work out of what to ask for help on, make it easier to say hello and get started!</p>
        </div>
      </div>

      
    </div>

    <div class="jumbotron">
      <div class="panel panel-default">
        <div class="panel-body">
          <h1>
            <span class="glyphicon glyphicon-envelope" aria-hidden="true"></span>
            Request Appointments and Pair
          </h1>
          <p class="col-lg-4 col-lg-offset-4">Once you choose a mentor, its easy to set up an appointment. Just complete the online form and mentorSHIP will do the rest!</p>
        </div>
      </div>

      <div class="container marketing">
        <div class="row">
          <div class="col-lg-6 col-lg-offset-3">
            <%=image_tag("turing.png", class: "img-circle", size: "200x200") %>
            <p>Get Started Now!</p>
            <p>
              <% if current_user == nil %>
              <%= link_to "Login with GitHub", "auth/github", class: "btn btn-lg btn-default" %>
              <% end %>
              </p>
          </div><!-- /.col-lg-4 -->
        </div><!-- /.row -->
      </div>
    </div>
  </div>
</div>
</div>

app/views/static_pages/profile_type_prompt.html.erb
<div class="jumbotron">
  <div class="row">
  <p><h3>What type of user are you?</h3></p>
    <div class="col-lg-4  col-lg-offset-4">
      <%= form_for @user do |f| %>
        <%= hidden_field_tag :profile_type, "students" %>
        <h4><%= f.submit "I'm a Student", class: "btn btn-lg btn-info" %></h4>
      <% end %>

      <%= form_for @user do |f| %>
        <%= hidden_field_tag :profile_type, "mentors" %>
        <h4><%= f.submit "I'm a Mentor", class: "btn btn-lg btn-warning" %>
      <% end %>
    </div>

  </div>
</div>