config/routes.rb
Rails.application.routes.draw do

  root to: 'static_pages#index'

  get '/auth/:provider/callback', to: 'sessions#create'
  get '/signout',                 to: 'sessions#destroy', as: 'signout'
  get '/search',                  to: 'mentors#search'
  get 'profile_type_prompt',      to: 'static_pages#profile_type_prompt'

  post 'notifications/notify',    to: 'notifications#notify'

  resources :snippets, only: [:new]
  resources :preferences
  resources :mentors
  resources :skills
  resources :students
  resources :users, only: [:update]
  resources :appointments, only: [:create]


end

app/models/student.rb
class Student < ActiveRecord::Base
  validates  :name,
             :email,
             :cohort, 
             :mod_id, 
             :posse_id, presence: true, on: :update

  belongs_to :mod
  belongs_to :posse

  has_attached_file :avatar, :styles => { medium: "300x300>", thumb: "150x150"},
  :default_url => "turing.png"

  validates_attachment_content_type :avatar, content_type: /\Aimage\/.*\Z/

  def is_user?(current_user, student)
    current_user.profile_id == student.id
  end
end

app/controllers/students_controller.rb
class StudentsController < ApplicationController
  before_action :set_student,  only: [:show, :edit, :update, :destroy]
  before_action :user_checker, only: [:show]

  def index
    @students = Student.all
  end

  def show
    @module   = @student.mod
    @projects = @module.projects
  end

  def new
    @student = Student.new
  end

  def create
    @student = Student.new(student_params)

    if @student.save
      flash[:success] = 'Your profile was successfully saved!'
      redirect_to student_path(@student)
    else
      render :new
    end
  end

  def edit
  end

  def update
    if @student.update(student_params)
      flash[:success] = 'Your profile was successfully updated!'
      redirect_to student_path(@student)
    else
      flash[:danger]  = "* = required fields"
      render :edit
    end
  end

  private

  def student_params
    params.require(:student).permit(:name,
                                    :email,
                                    :bio,
                                    :cohort,
                                    :mod_id,
                                    :posse_id,
                                    :avatar)
  end

  def set_student
    @student = Student.find(params[:id])
  end

  def user_checker
    if current_user  == nil
      flash[:danger] = "You must be signed in to view student profiles"
      redirect_to "/"
    else
      profile_checker
    end
  end

  def profile_checker
    if current_user.profile_type == nil
      redirect_to profile_type_prompt_path
      flash[:danger] = "You must select a profile type to continue"
    end
  end

  def is_user?(current_user)
    current_user.id == @student.id
  end
end

app/views/students/_errors.html.erb
<% if @student.errors.any? %>
<div id="error_explanation">
  <h4><%= pluralize(@student.errors.count, "error") %> prohibited this profile from being saved:</h4>
    <% @student.errors.full_messages.each do |message| %>
    <%= message %>&nbsp
    <% end %>
</div>
<% end %>

app/views/students/_form.html.erb
<%= form_for(@student, html: { :class => "form-horizontal"}) do |f| %>
  <div class="form-group has-feedback">
    <div class="col-md-6 col-md-offset-3">
      <%= f.text_field :name, class: "form-control", placeholder: "* Name"  %>
    </div>
  </div>
  <div class="form-group has-feedback">
    <div class="col-md-6 col-md-offset-3">
      <%= f.text_field :email, class: "form-control", placeholder: "* Email@example.com"  %>
    </div>
  </div>
  <div class="form-group has-feedback">
    <div class="col-md-6 col-md-offset-3">
      <%= f.text_area :bio, class: "form-control", placeholder: "A bit about you . . . " %>
    </div>
  </div>
  <div class="form-group has-feedback">
    <div class="col-md-6 col-md-offset-3">
      <%= f.text_field :cohort, class: "form-control", placeholder: "* Cohort: 1406, 1502, etc." %>
    </div>
  </div>
  <div class="form-group has-feedback">
    <div class="col-md-6 col-md-offset-3">
      * <%= f.label :module, class: "control-label" %>
      <div class="radio-inline">
        <label>
          <%= f.collection_radio_buttons(:mod_id, Mod.all, :id, :name) do |b| %>
          <%= b.radio_button %>
          <%= b.label %>&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp
          <% end %>
        </label>
      </div>
    </div>
  </div>
  <div class="form-group has-feedback">
    <div class="col-md-6 col-md-offset-3">
      * <%= f.label :posse, class: "control-label" %>
      <%= f.select(:posse_id, options_from_collection_for_select(Posse.all, "id", "name"), {}, {class: "form-control"})%>
    </div>
  </div>
  <div class="form-group has-feedback">
    <div class="col-md-6 col-md-offset-3">
      <%= f.label :photo, class: "control-label" %>
      <%= f.file_field :avatar, class: "form-control" %>
    </div>
  </div>
  <div class="form-group">
    <div class="col-md-6 col-md-offset-3">
      <%= f.submit "Save Profile", class: "btn btn-large btn-info" %>
    </div>
  </div>
<% end %>

app/views/students/edit.html.erb
<%= render partial: "errors" %>
<h2><center>Update Your Profile</center></h2>
<%= render partial: "form" %>

app/views/students/index.html.erb
<h2>Students at Turing</h2>
<br/>
<div class="row">
  <% @students.each do |s| %>
  <div class="col-sm-6 col-md-4">
    <div class="thumbnail">
      <%= image_tag s.avatar.url(:thumb), class: "img-circle" %>
      <div class="caption">
        <h2><%= link_to s.name, student_path(s) %></h2>
        <p>
          <%= s.cohort %><br/>
          <%= s.mod.name %>
        </p>
      </div>
    </div>
  </div>
  <% end %>
</div>

app/views/students/new.html.erb
<h2><center>Create Your Profile</center></h2>
<%= render partial: "form" %>

app/views/students/show.html.erb
<h2><%= @student.name %></h2>
<div class="container">
  <div class="student-row">
    <div class="col-md-4 col-md-offset-1 blog-sidebar">
      <div class="sidebar-module">
        <%= image_tag @student.avatar.url(:medium), class: "img-circle" %>
        <br/><br/>
        <b>Cohort:</b> <%= @student.cohort %><br/>
        <b>Module:</b> <%= @student.mod.name %><br/>
        <b>Posse:</b> <%= @student.posse.name %><br/><br/>
        <% if @student.is_user?(current_user, @student) %>
          <%= link_to "Edit your profile", edit_student_path(@student), class: "btn btn-xs btn-default" %>
        <% end %>
      </div>
    </div>
    <div class="col-md-7">
      <p>
        <br/>
        <%= @student.bio %>
      </p>
      <p>
        <h3>Module Rundown:</h3> <%= @student.mod.name %>: <%= @student.mod.description %>
      </p>
      <p>
        <h3>Projects in this Module:</h3>
        <% @projects.each do |p| %>
          <b><%= p.name %></b>
          <p>Description: <%= p.description %></p>
          <p>Link to Project Spec: <%= link_to "#{p.url}", p.url  %></p>
        <% end %>
      </p>
    </div>
  </div>
</div>