config/routes.rb
Rails.application.routes.draw do

  root to: 'static_pages#index'

  get '/auth/:provider/callback', to: 'sessions#create'
  get '/signout',                 to: 'sessions#destroy', as: 'signout'
  get '/search',                  to: 'mentors#search'
  get 'profile_type_prompt',      to: 'static_pages#profile_type_prompt'

  post 'notifications/notify',    to: 'notifications#notify'

  resources :snippets, only: [:new]
  resources :preferences
  resources :mentors
  resources :skills
  resources :students
  resources :users, only: [:update]
  resources :appointments, only: [:create]


end

app/models/mentor.rb
class Mentor < ActiveRecord::Base
  validates :name,
            :email, presence: :true, on: :update

  has_many  :mentor_skills
  has_many  :skills, through: :mentor_skills
  has_many  :preferences

  has_attached_file :photo, :styles => { medium: "300x300>", thumb: "150x150"},
  :default_url => "turing.png"


  validates_attachment_content_type :photo, content_type: /\Aimage\/.*\Z/

  def is_user?(current_user, mentor)
    current_user.profile_id == mentor.id
  end
end

app/controllers/mentors_controller.rb
class MentorsController < ApplicationController
  before_action :set_mentor,   only: [:show, :edit, :update]
  before_action :set_student,  only: [:show]
  before_action :user_checker, only: [:show]

  def index
    @mentors = Mentor.includes(:skills)
    @skills  = Skill.all

    if params[:filter]
      @mentors = @mentors.find_all { |m| m.skills.collect { |s| s.name }.include?(params[:filter]) }
    end
  end

  def show
    @appointment         = Appointment.new
    @notification        = Notification.new
    @contact_preferences = find_preferences
  end

  def new
    @mentor = Mentor.new
    @skills = Skill.all
  end

  def create
    @mentor = Mentor.new(mentor_params)

    if @mentor.save
      add_mentor_skills
      flash[:success] = "Profile was successfully create"
      redirect_to mentor_path(@mentor)
    else
      flash[:danger]  = "* = required field"
      render :new
    end
  end

  def edit
  end

  def update
    @mentor.update(mentor_params)

    if @mentor.update(mentor_params)
      add_mentor_skills
      flash[:success] = "Profile was successfully updated"
      redirect_to mentor_path(@mentor)
    else
      flash[:danger]  = "* = required fields"
      render :edit
    end
  end

  def search
    @mentors = Mentor.find_matches(params[:query])
  end


private

  def add_mentor_skills
    set_skills     = Skill.where(id: params[:mentor][:skills])
    @mentor.skills = set_skills
  end

  def set_mentor
    @mentor = Mentor.find(params[:id])
  end

  def set_student
    if current_user.profile_type == "student"
      @student = Student.find(params[:id])
    end
  end

  def mentor_params
    params.require(:mentor).permit(:name,
                                   :email,
                                   :company,
                                   :bio,
                                   :photo,
                                   :skills,
                                   :phone_number,
                                   :preferences)
  end

  def user_checker
    if current_user  == nil
      flash[:danger] = "You must be signed in to do that"
      redirect_to "/"
    else
      profile_checker
    end
  end

  def profile_checker
    if current_user.profile_type == nil
      redirect_to profile_type_prompt_path
      flash[:danger] = "You must select a profile type to continue"
    end
  end

  def find_preferences
    @mentor.preferences.collect {|p| p.name }
  end
end

app/views/mentors/_form.html.erb
<div class="form">
<%= form_for @mentor, :html => {multipart: true, class: "form-horizontal"} do |f| %>
  <div>
    <div class="form-group">
      <div class="col-md-6 col-md-offset-3">
        <%= f.text_field :name, :class => "form-control", :placeholder => "Name *" %>
      </div>
    </div>

    <div class="form-group">
      <div class="col-md-6 col-md-offset-3">
        <%= f.text_field :email, :class => "form-control", :placeholder => "email@example.com *" %>
      </div>
    </div>

    <div class="form-group">
      <div class="col-md-6 col-md-offset-3">
        <%= f.text_field :company, :class => "form-control", :placeholder => "employer" %>
      </div>
    </div>

    <div class="form-group">
      <div class="col-md-6 col-md-offset-3">
        <%= f.text_area :bio, :class => "form-control", :placeholder => "Write a short bio" %>
      </div>
    </div>

    <div class="form-group">
      <div class="col-md-6 col-md-offset-3">
        <%= f.label "Contact Preference(s) *" %>
        <br/>
        <%= f.collection_check_boxes(:preferences, Preference.all, :id, :name) do |b| %>
          <%= b.check_box %>
          <%= b.label(class: "check-box") %>&nbsp&nbsp
        <% end %>
      </div>
    </div>

    <div class="form-group">
      <div class="col-md-6 col-md-offset-3">
        <%= f.telephone_field :phone_number, :class => "form-control", :placeholder => "Provide if you allow text-request appointments. (xxx-xxx-xxxx)" %>
      </div>
    </div>

    <div class="form-group">
      <div class="col-md-6 col-md-offset-3">
        <%= f.label "Profile Photo (optional)", class: "form-label" %>
        <%= f.file_field :photo, class: 'form-control'%>
      </div>
    </div>

    <div class="form-group">
      <div class="col-md-6 col-md-offset-3">
        <%= f.label "Best At (select all that apply) *", class: "form-label"%>
      </div>
        <div class="col-md-6 col-md-offset-3">
        <%= f.collection_check_boxes(:skills, Skill.all, :id, :name) do |b| %>
          <%= b.check_box %>
          <%= b.label(class: "check-box")  %>&nbsp
        <% end %>
        </div>
    </div>

    <div class="form-group">
      <div class="col-md-6 col-md-offset-3">
        <%= f.submit "Submit", :class => 'btn btn-lg btn-primary' %>
      </div>
    </div>
  </div>
<% end %>
</div>

app/views/mentors/edit.html.erb
<h2><center>Edit your profile <%= @mentor.name %></center></h2>
<%= render partial: "form" %>
</div>

app/views/mentors/index.html.erb
  <div class="container marketing">
    <h2>Filter Mentors by Skills</h2>
    <div class="btn-toolbar" role="toolbar" aria-label="...">
      <div class="btn-group" role="group" aria-label="...">
        <% @skills.each do |s| %>
          <%= link_to s.name, mentors_path(filter: s.name), class: "btn btn-primary" %>
        <% end %>
      </div
      <div class="btn-group" role="group" aria-label="...">
        <%= link_to "All Mentors", mentors_path, class: "btn btn-primary" %>
      </div>
      <br/>
      <br/>
      <br/>
    </div>

<div class="row">
  <% cache @mentors do %>
    <% @mentors.each do |m| %>
  <div class="col-sm-6 col-md-4">
    <div class="thumbnail">
      <%= image_tag m.photo.url(:thumb), class: "img-circle" %>
      <div class="caption">
        <h3><%= link_to m.name, mentor_path(m) %></h3>
        <p>
          <% m.skills.each do |skill| %>
            <%= skill.name %> &nbsp
          <% end %>
        </p>
      </div>
    </div>
  </div>
    <% end %>
  <% end %>
</div>

app/views/mentors/new.html.erb
<div class="form-panel">
  <div class="panel-heading">
    <h3 class="panel-title">Complete your profile</h3>
  </div>
  <%= render partial: "form" %>
</div>

app/views/mentors/search.html.erb
<h1>Mentors matching your search</h1>
<br/>
<div class="container marketing">
  <div class="row">
    <% @mentors.each do |m| %>
    <div class="col-lg-4">
      <%= image_tag m.photo, class: "img-circle", style: "width: 140px; height: 140px;" %>
      <h2><%= link_to m.name, mentor_path(m) %></h2>
      <p>
        <% m.skills.each do |skill| %>
        <%= skill.name %> &nbsp
        <% end %>
      </p>
    </div><!-- /.col-lg-4 -->
    <% end %>
  </div><!-- /.row -->
</div><!-- /.container marketing -->

app/views/mentors/show.html.erb
<h2><%= @mentor.name %></h2>
<div class="container">
  <div class="mentor-row">
    <div class="col-md-4 col-md-offset-1 blog-sidebar">
      <div class="sidebar-module">
        <%= image_tag @mentor.photo.url(:medium), class: "img-circle" %>
        <br/><br/>
        <% if @mentor.is_user?(current_user, @mentor) %>
          <%= link_to "Edit your profile", edit_mentor_path(@mentor), class: "btn btn-xs btn-default" %><br/><br/>
        <% end %>
        <b>Email:</b> <%= @mentor.email %><br/>
        <b>Employer:</b> <%= @mentor.company %><br/>
        <b>Best at:</b>
        <% @mentor.skills.each do |skill| %>
          <ul>
            <li><%= skill.name %></li>
          </ul>
          <% end %>
      </div>
    </div>
    <div class="col-md-5">
      <p>
        <br/>
        <%= @mentor.bio %>
      </p>
    </div><br/>
  </div>
    <div class="col-md-4">
    <% if current_user.student %>
      <p>
        <% if @contact_preferences.include?("email") %>
          <%= link_to "Reach out to #{@mentor.name} by Email", "#emailModal", "data-toggle" => "modal", class: "btn btn-small btn-default" %>
        <% end %>
      </p>
      <p>
        <% if @contact_preferences.include? "email" %>
          <%= link_to "Reach out to #{@mentor.name} by SMS", "#smsModal", "data-toggle" => "modal", class: "btn btn-small btn-default" %>
        <% end %>
      </p>
    <% end %>
  </div>
</div>

<% if current_user.student %>
  <%= render "modals/email_appointment_modal" %>
  <%= render "modals/sms_appointment_modal" %>
<% end %>