config/routes.rb
Rails.application.routes.draw do

  root to: 'static_pages#index'

  get '/auth/:provider/callback', to: 'sessions#create'
  get '/signout',                 to: 'sessions#destroy', as: 'signout'
  get '/search',                  to: 'mentors#search'
  get 'profile_type_prompt',      to: 'static_pages#profile_type_prompt'

  post 'notifications/notify',    to: 'notifications#notify'

  resources :snippets, only: [:new]
  resources :preferences
  resources :mentors
  resources :skills
  resources :students
  resources :users, only: [:update]
  resources :appointments, only: [:create]


end

app/models/appointment.rb
require 'active_model'

class Appointment
  include ActiveModel::Model

  attr_accessor :mentor, 
                :student, 
                :subject, 
                :body
end

app/models/comment.rb
class Comment < ActiveRecord::Base
  validates :body, presence: true
end

app/models/mentor.rb
class Mentor < ActiveRecord::Base
  validates :name,
            :email, presence: :true, on: :update

  has_many  :mentor_skills
  has_many  :skills, through: :mentor_skills
  has_many  :preferences

  has_attached_file :photo, :styles => { medium: "300x300>", thumb: "150x150"},
  :default_url => "turing.png"


  validates_attachment_content_type :photo, content_type: /\Aimage\/.*\Z/

  def is_user?(current_user, mentor)
    current_user.profile_id == mentor.id
  end
end

app/models/mentor_skill.rb
class MentorSkill < ActiveRecord::Base
  belongs_to :mentor
  belongs_to :skill
end

app/models/mod.rb
class Mod < ActiveRecord::Base
  has_many :students
  has_many :projects

  validates :number,
            :name,
            :description, presence: true
end

app/models/notification.rb
require 'active_model'

class Notification
  include ActiveModel::Model

  attr_accessor :number,
                :student, 
                :body
end

app/models/posse.rb
class Posse < ActiveRecord::Base
end

app/models/preference.rb
class Preference < ActiveRecord::Base
  belongs_to :mentors
end

app/models/project.rb
class Project < ActiveRecord::Base
  belongs_to :mod
end

app/models/skill.rb
class Skill < ActiveRecord::Base
  validates :name, presence: :true

  has_many :mentor_skills
  has_many :mentors, through: :mentor_skills
end

app/models/snippet.rb
class Snippet < ActiveRecord::Base
  validates :title, 
            :body, presence: true
end

app/models/student.rb
class Student < ActiveRecord::Base
  validates  :name,
             :email,
             :cohort, 
             :mod_id, 
             :posse_id, presence: true, on: :update

  belongs_to :mod
  belongs_to :posse

  has_attached_file :avatar, :styles => { medium: "300x300>", thumb: "150x150"},
  :default_url => "turing.png"

  validates_attachment_content_type :avatar, content_type: /\Aimage\/.*\Z/

  def is_user?(current_user, student)
    current_user.profile_id == student.id
  end
end

app/models/user.rb
class User < ActiveRecord::Base

  belongs_to :student
  belongs_to :mentor

  def student
    Student.find(profile_id) if profile_type == 'students'
  end

  def mentor
    Mentor.find(profile_id) if profile_type == 'mentors'
  end

  def self.from_omniauth(auth)
    user = User.find_or_create_by(uid: auth.uid)
    user
  end
end

app/controllers/mentors_controller.rb
class MentorsController < ApplicationController
  before_action :set_mentor,   only: [:show, :edit, :update]
  before_action :set_student,  only: [:show]
  before_action :user_checker, only: [:show]

  def index
    @mentors = Mentor.includes(:skills)
    @skills  = Skill.all

    if params[:filter]
      @mentors = @mentors.find_all { |m| m.skills.collect { |s| s.name }.include?(params[:filter]) }
    end
  end

  def show
    @appointment         = Appointment.new
    @notification        = Notification.new
    @contact_preferences = find_preferences
  end

  def new
    @mentor = Mentor.new
    @skills = Skill.all
  end

  def create
    @mentor = Mentor.new(mentor_params)

    if @mentor.save
      add_mentor_skills
      flash[:success] = "Profile was successfully create"
      redirect_to mentor_path(@mentor)
    else
      flash[:danger]  = "* = required field"
      render :new
    end
  end

  def edit
  end

  def update
    @mentor.update(mentor_params)

    if @mentor.update(mentor_params)
      add_mentor_skills
      flash[:success] = "Profile was successfully updated"
      redirect_to mentor_path(@mentor)
    else
      flash[:danger]  = "* = required fields"
      render :edit
    end
  end

  def search
    @mentors = Mentor.find_matches(params[:query])
  end


private

  def add_mentor_skills
    set_skills     = Skill.where(id: params[:mentor][:skills])
    @mentor.skills = set_skills
  end

  def set_mentor
    @mentor = Mentor.find(params[:id])
  end

  def set_student
    if current_user.profile_type == "student"
      @student = Student.find(params[:id])
    end
  end

  def mentor_params
    params.require(:mentor).permit(:name,
                                   :email,
                                   :company,
                                   :bio,
                                   :photo,
                                   :skills,
                                   :phone_number,
                                   :preferences)
  end

  def user_checker
    if current_user  == nil
      flash[:danger] = "You must be signed in to do that"
      redirect_to "/"
    else
      profile_checker
    end
  end

  def profile_checker
    if current_user.profile_type == nil
      redirect_to profile_type_prompt_path
      flash[:danger] = "You must select a profile type to continue"
    end
  end

  def find_preferences
    @mentor.preferences.collect {|p| p.name }
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def create
    auth = request.env["omniauth.auth"]
    user = User.from_omniauth(auth)
    session[:user_id] = user.id
    user
    redirect_to root_url
  end

  def destroy
    session[:user_id] = nil
    redirect_to root_path
  end
end

app/controllers/skills_controller.rb
class SkillsController < ApplicationController
end

app/controllers/snippets_controller.rb
class SnippetsController < ApplicationController
  def new
  end
end

app/controllers/students_controller.rb
class StudentsController < ApplicationController
  before_action :set_student,  only: [:show, :edit, :update, :destroy]
  before_action :user_checker, only: [:show]

  def index
    @students = Student.all
  end

  def show
    @module   = @student.mod
    @projects = @module.projects
  end

  def new
    @student = Student.new
  end

  def create
    @student = Student.new(student_params)

    if @student.save
      flash[:success] = 'Your profile was successfully saved!'
      redirect_to student_path(@student)
    else
      render :new
    end
  end

  def edit
  end

  def update
    if @student.update(student_params)
      flash[:success] = 'Your profile was successfully updated!'
      redirect_to student_path(@student)
    else
      flash[:danger]  = "* = required fields"
      render :edit
    end
  end

  private

  def student_params
    params.require(:student).permit(:name,
                                    :email,
                                    :bio,
                                    :cohort,
                                    :mod_id,
                                    :posse_id,
                                    :avatar)
  end

  def set_student
    @student = Student.find(params[:id])
  end

  def user_checker
    if current_user  == nil
      flash[:danger] = "You must be signed in to view student profiles"
      redirect_to "/"
    else
      profile_checker
    end
  end

  def profile_checker
    if current_user.profile_type == nil
      redirect_to profile_type_prompt_path
      flash[:danger] = "You must select a profile type to continue"
    end
  end

  def is_user?(current_user)
    current_user.id == @student.id
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def update
    @user = current_user

    if profile_type == 'students'
      student = Student.create
      @user.update!(profile_type: profile_type, profile_id: student.id)
      redirect_to edit_student_path(student)
    else 
      mentor = Mentor.create
      @user.update!(profile_type: profile_type, profile_id: mentor.id)
      redirect_to edit_mentor_path(mentor)
    end
  end

  private

  def profile_type
    params.require(:profile_type)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper

  def resource_name
    :appointment
  end

  def resource
    @appointment = Appointment.new
  end
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="mentorSHIP application for Turing">
    <meta name="author" content="Chad Brading, Corey Davis, Emily Davis, Tim Proctor 1406 cohort 2014">

    <title>mentorSHIP</title>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
    <script src="https://raw.github.com/jiren/filter.js/master/filter.js" type="text/javascript"></script>
    <%= csrf_meta_tags %>

  </head>

  <body>
    <%= render partial: "shared/navbar" %>
    <%= render partial: "shared/messages" %>
    <%= yield %>
    <%= javascript_include_tag "application" %>
  </body>
   <%= render partial: "shared/footer"%>
</html>

app/views/modals/_appointment_modal.html.erb
<div class="modal fade" id="apptModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">

  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal"><span aria-hidden="true">&times;</span><span class="sr-only">Close</span></button>
        <h4 class="modal-title" id="myModalLabel">Contact <%= @mentor.name %> an Appointment</h4>
      </div>

      <div class="modal-body">
        <%= form_for(resource, as: resource_name) do |f| %>
          <div class='form-group'>
            To: <%= @mentor.name %>
            From: <%= current_user.student.name %>
          </div>
          <div class="form-group">
            <%= f.text_field :subject, class: "form-control", placeholder: "Subject" %>
            <%= f.hidden_field :mentor, value: @mentor.id %>
            <%= f.hidden_field :student, value: current_user.student.id %>
          </div>
          <div class="form-group">
            <%= f.text_area :body, class: "form-control", placeholder: "Message" %>
          </div>
          <div class="form-group">
            <%= f.submit "Send Request", class: "btn btn-primary btn-small" %>
          </div>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/modals/_email_appointment_modal.html.erb
<div class="modal fade" id="emailModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">

  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal"><span aria-hidden="true">&times;</span><span class="sr-only">Close</span></button>
        <h4 class="modal-title" id="myModalLabel">Email <%= @mentor.name %></h4>
      </div>

      <div class="modal-body">
        <%= form_for(resource, as: resource_name) do |f| %>
          <div class='form-group'>
            <b>To:</b> <%= @mentor.name %><br/>
            <b>From:</b> <%= current_user.student.name %>
          </div>
          <div class="form-group">
            <%= f.text_field :subject, class: "form-control", placeholder: "Subject" %>
            <%= f.hidden_field :mentor, value: @mentor.id %>
            <%= f.hidden_field :student, value: current_user.student.id %>
          </div>
          <div class="form-group">
            <%= f.text_area :body, class: "form-control", placeholder: "Message" %>
          </div>
          <div class="form-group">
            <%= f.submit "Send", class: "btn btn-primary btn-small" %>
          </div>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/modals/_sms_appointment_modal.html.erb
<div class="modal fade" id="smsModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">

  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal"><span aria-hidden="true">&times;</span><span class="sr-only">Close</span></button>
        <h4 class="modal-title" id="myModalLabel">Send an SMS to <%= @mentor.name %></h4>
      </div>

      <div class="modal-body">
        <%= form_for @notification, url: notifications_notify_path do |f| %>
        <div class="form-group">
          <%= f.hidden_field :number, value: @mentor.phone_number %>
          <%= f.hidden_field :student, value: current_user.student.name %>
          <%= f.text_area :body, class: "form-control", placeholder: "Message, don't forget to include your ph# if you want a text back" %>
        </div>
        <div class="form-group">
          <%= f.submit "Send", class: "btn btn-sm btn-primary" %>
        </div>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/shared/_footer.html.erb
<footer class="row">
    <div class="col-lg-12">
      <br/>
      <p>&copy; 2014 Turing School of Software &amp Design &middot; Cohort 1406 &middot; All Rights Reserved</p>
      <br/>
    </div>
</footer>

app/views/shared/_messages.html.erb
<div class="alert-background text-center">
  <% flash.each do |type, message| %>
<div class="alert alert-<%= type %>">
  <%= message %>
</div>
  <% end %>
</div>

app/views/shared/_navbar.html.erb
<header class="mod-header">
  <div class="layout-wrap">
    <h1 class="logo">
      <a href="http://turing.io">Turing School of Software and Design</a>
    </h1>
    <nav>
      <ul>
        <li>
          <form action="/search" class="search">
            <input type="text" name="query" placeholder="Search Mentors" class="search-text-box">
          </form>
        </li>
        <li>&nbsp</li>
        <li><%= link_to "Home", root_path %></li>
        <% if current_user %>
          <% if current_user.mentor %>
            <li><%= link_to "Students", students_path %></li>
            <li><%= link_to "Profile", mentor_path(current_user.mentor)  %></li>
          <% elsif current_user.student %>
            <li><%= link_to "Mentors", mentors_path %></li>
            <li><%= link_to "Profile", student_path(current_user.student) %></li>
          <% else %>
            <li><%= link_to "SET UP ACCOUNT", profile_type_prompt_path %></li> 
          <% end %>
          <li><%= link_to "Sign Out", signout_path %></li>
        <% else %>
          <li><%= link_to "Sign In", '/auth/github/' %></li>
        <% end %>
      </ul>
    </nav>
  </div>
</header>